---
title: "Conservancy Analysis"
author: "BEACN"
date: "March 23, 2018"
output:
  html_document: default
  pdf_document: default
---

## Setup

Downloading the data

```{r Downloading Necessary Data}
library(Hmisc)
library(ggplot2)
library(stringr)
library(gridExtra)
library(tidyverse)
library(knitr)
library(kableExtra)
library(plotly)
library(RcppRoll)
library(cowplot)
library(RColorBrewer)

conservancy_names <- function(name) {
  return(paste0("conservancy_", name, ".csv")) 
}

ucnrs_names <- function(name) {
  return(paste0("ucnrs_", name, ".csv"))
}

conservancyNames <- c("birds", "herpetofauna", "invertebrates", "mammals", "plants")

ucnrsNames <- c("animal_list", "plant_list")

fullConservancyNames <- conservancy_names(conservancyNames)
fullUCNRSNames <- ucnrs_names(ucnrsNames)

allFiles <- c(fullConservancyNames, fullUCNRSNames)
path <- paste0("./ucnrs_data/", allFiles)

data <- lapply(path, read_csv) 
head(data)

```

## Combining UCNRS and Conservancy into four datasets


```{r Combining Datasets}

# Separating out columns of data for conservancy data and removing irrelevant values

conservancyAnimalData <- bind_rows(data[[1]], data[[2]], data[[3]], data[[4]]) %>% 
  distinct(species) %>% 
  separate(species, into = c("genus", "species", "sublabel1", "sublabel2"), sep = " ", extra = "merge") %>% 
  filter(!(genus %in% c("Tejon", "Undefined"))) %>% 
  filter(!is.na(species))

conservancyPlantData <- data[[5]] %>% 
  distinct(species) %>% 
  separate(species, into = c("genus", "species", "separator_label", "sublabel"), sep = " ", extra = "merge") %>% 
  filter(!(genus %in% c("Tejon", "Undefined"))) %>% 
  filter(!is.na(species))

# Loading Plant and Animal data from UCNRS

ucnrsPlantData <- data[[7]]
ucnrsAnimalData <- data[[6]]

# Relabeling data

names(ucnrsPlantData)[7:8] <- c("separator_label", "sublabel")
names(ucnrsAnimalData)[4] <- "scientific_name"

# Cleaning UCNRS Animal data

ucnrsAnimalDataSubset <- ucnrsAnimalData %>% 
  mutate(scientific_name = gsub("\\(", "", scientific_name), 
         scientific_name = gsub("\\)", "", scientific_name),
         scientific_name = gsub("\\.", "", scientific_name), 
         scientific_name = iconv(scientific_name, "utf-8", "ascii", sub=" "),
         Reserve = iconv(Reserve, "utf-8", "ascii", sub="n")) %>% 
  select(Reserve, scientific_name) %>% 
  separate(scientific_name, into = c("genus", "species", "sublabel1", "sublabel2"), sep = " ", extra = "merge") %>%
  mutate(species = tolower(species)) %>% 
  filter(!is.na(species)) %>% 
  rename(reserve = Reserve) %>% 
  mutate(reserve = gsub(" Reserve", "", reserve),
         reserve = gsub(" Marine", "", reserve),
         reserve = gsub(" Desert Research Center", "", reserve),
         reserve = gsub(" Natural", "", reserve),
         reserve = gsub(" History", "", reserve),
         reserve = gsub("Missions", "Mission", reserve),
         reserve = gsub("Landells-Hill", "Landels-Hill", reserve),
         reserve = gsub("Landels Hil", "Landels-Hill", reserve),
         reserve = gsub(" Field Station", "", reserve),
         reserve = gsub(" Santa Monica Mountains", "", reserve),
         reserve = gsub("Sedgewick", "Sedgwick", reserve),
         reserve = gsub("Valentine.*", "Valentine Eastern Sierra", reserve)) %>% 
  distinct()

# Cleaning UCNRS Plant Data

ucnrsPlantDataSubset <- ucnrsPlantData %>% 
  select(Reserve, Genus, Species, separator_label, sublabel) %>%
  rename(reserve = Reserve, genus = Genus, species = Species) %>% 
  filter(!is.na(species)) %>% 
  mutate(reserve = gsub(" Reserve", "", reserve),
         reserve = gsub(" Marine", "", reserve),
         reserve = gsub(" Desert Research Center", "", reserve),
         reserve = gsub(" Natural", "", reserve),
         reserve = gsub(" History", "", reserve),
         reserve = gsub("Missions", "Mission", reserve),
         reserve = gsub("Landells-Hill", "Landels-Hill", reserve),
         reserve = gsub("Landels Hil", "Landels-Hill", reserve),
         reserve = gsub(" Field Station", "", reserve),
         reserve = gsub(" Santa Monica Mountains", "", reserve),
         reserve = gsub("Sedgewick", "Sedgwick", reserve),
         reserve = gsub("Valentine.*", "Valentine Eastern Sierra", reserve)) %>% 
  distinct()

# Rename repeated reserves
reserveNames <- sort(unique(c(ucnrsPlantDataSubset$reserve, ucnrsAnimalDataSubset$reserve)))
reserveNames

# Print results

head(ucnrsAnimalDataSubset)
head(ucnrsPlantDataSubset)
head(conservancyAnimalData)
head(conservancyPlantData)


```

## Match Ratio of Species per Reserve

```{r Create Plant Table}

# Find shared genies and species of plants
matchingPlants <- semi_join(ucnrsPlantDataSubset, conservancyPlantData, by = c("genus", "species", "sublabel")) %>%
  select(reserve, genus, species, sublabel)

# Calculate how similar plant species composition is by reserve
matchingPlantsCount <- matchingPlants %>% 
  group_by(reserve) %>% 
  filter(!is.na(reserve)) %>% 
  summarize(matching_plant_species = n())

# Find total plant species per reserve
totalPlantsCount <- ucnrsPlantDataSubset %>% 
  group_by(reserve) %>% 
  filter(!is.na(reserve)) %>% 
  summarize(total_plant_species_in_reserve = n())

# Total plant count for conservancy
total_plant_species_in_conservancy <- nrow(conservancyPlantData)

# Create tables comparing proportion of plants in conservancy also in reserve and vice versa 
plantsComparisonTable <- left_join(matchingPlantsCount, totalPlantsCount, 
                                   by = "reserve") %>% 
  mutate(proportion_matching_plant_species_in_reserve = 
           matching_plant_species / total_plant_species_in_reserve) %>% 
  mutate(percent_matching_plant_species_in_reserve = 
           paste0(format(100 * proportion_matching_plant_species_in_reserve, 
         digits = 2), "%")) %>% 
  mutate(proportion_matching_plant_species_in_conservancy = 
           matching_plant_species / total_plant_species_in_conservancy) %>% 
  mutate(percent_matching_plant_species_in_conservancy = 
           paste0(format(100 * proportion_matching_plant_species_in_conservancy, 
         digits = 1), "%")) %>% 
  arrange(desc(proportion_matching_plant_species_in_reserve)) 

plantsComparisonTableConservancyEmphasis <- plantsComparisonTable %>% 
  arrange(desc(proportion_matching_plant_species_in_conservancy)) %>% 
  select(reserve, matching_plant_species, total_plant_species_in_reserve, 
         percent_matching_plant_species_in_reserve, percent_matching_plant_species_in_conservancy)

plantsComparisonTableShort <- plantsComparisonTable %>% 
  select(reserve, matching_plant_species, total_plant_species_in_reserve, 
         percent_matching_plant_species_in_reserve, percent_matching_plant_species_in_conservancy)

# Visualize results
plantsComparisonTableViz <- plantsComparisonTableShort %>% 
  kable(format = "html", align = "lcccc",
        col.names = gsub("_", " ", capitalize(colnames(plantsComparisonTableShort)))) %>% 
  kable_styling

plantsComparisonTableConservancyEmphasisViz <- plantsComparisonTableConservancyEmphasis %>% 
  kable(format = "html", align = "lcccc",
        col.names = gsub("_", " ", capitalize(colnames(plantsComparisonTableConservancyEmphasis)))) %>% 
  kable_styling

plantsComparisonTableViz
plantsComparisonTableConservancyEmphasisViz

```

```{r Create Animal Table}
# Find shared genies and species of animals
matchingAnimals <- semi_join(ucnrsAnimalDataSubset, conservancyAnimalData, by = c("genus", "species", "sublabel1")) %>%
  select(reserve, genus, species, sublabel = sublabel1)

# Calculate how similar animal species composition is by reserve
matchingAnimalsCount <- matchingAnimals %>% 
  group_by(reserve) %>% 
  filter(!is.na(reserve)) %>% 
  summarize(matching_animal_species = n()) 

totalAnimalsCount <- ucnrsAnimalDataSubset %>% 
  group_by(reserve) %>% 
  filter(!is.na(reserve)) %>% 
  summarize(total_animal_species_in_reserve = n())

# Total animal count for conservancy
total_animal_species_in_conservancy <- nrow(conservancyAnimalData)

# Create tables comparing proportion of plants in conservancy also in reserve and vice versa 

animalsComparisonTable <- left_join(matchingAnimalsCount, totalAnimalsCount, 
                                   by = "reserve") %>% 
  mutate(proportion_matching_animal_species_in_reserve = 
           matching_animal_species / total_animal_species_in_reserve) %>% 
  mutate(percent_matching_animal_species_in_reserve = 
           paste0(format(100 * proportion_matching_animal_species_in_reserve, 
         digits = 3), "%")) %>% 
  mutate(proportion_matching_animal_species_in_conservancy = 
           matching_animal_species / total_animal_species_in_conservancy) %>% 
  mutate(percent_matching_animal_species_in_conservancy = 
           paste0(format(100 * proportion_matching_animal_species_in_conservancy, 
         digits = 2), "%")) %>% 
  arrange(desc(proportion_matching_animal_species_in_reserve))

animalsComparisonTableConservancyEmphasis <- animalsComparisonTable %>% 
  arrange(desc(proportion_matching_animal_species_in_conservancy)) %>% 
  select(reserve, matching_animal_species, total_animal_species_in_reserve,
         percent_matching_animal_species_in_reserve, percent_matching_animal_species_in_conservancy)

animalsComparisonTableShort <- animalsComparisonTable %>% 
  select(reserve, matching_animal_species, total_animal_species_in_reserve,
         percent_matching_animal_species_in_reserve, percent_matching_animal_species_in_conservancy)

# Visualize results
animalsComparisonTableViz <- animalsComparisonTableShort %>% 
  kable(format = "html", align = "lcccc", 
        col.names = gsub("_", " ", capitalize(colnames(animalsComparisonTableShort)))) %>% 
  kable_styling

animalsComparisonTableConservancyEmphasisViz <- animalsComparisonTableConservancyEmphasis %>% 
  kable(format = "html", align = "lcccc", 
        col.names = gsub("_", " ", capitalize(colnames(animalsComparisonTableConservancyEmphasis)))) %>% 
  kable_styling

animalsComparisonTableViz
animalsComparisonTableConservancyEmphasisViz

```

```{r Create Total Species Count}

# Combine species data
matchingSpecies <- bind_rows("animals" = matchingAnimals, 
                             "plants" = matchingPlants,
                             .id = "kingdom") 

animalSpeciesDataStandardized <- ucnrsAnimalDataSubset %>% 
  select(reserve, genus, species, sublabel = sublabel1)
plantSpeciesDataStandardized <- ucnrsPlantDataSubset %>% 
  select(reserve, genus, species, sublabel)

combinedSpeciesData <- bind_rows(animalSpeciesDataStandardized, plantSpeciesDataStandardized)

conservancyAnimalSpeciesDataStandardized <- conservancyAnimalData %>% 
  select(genus, species, sublabel = sublabel1)
conservancyPlantSpeciesDataStandardized <- conservancyPlantData %>% 
  select(genus, species, sublabel)

conservancyCombinedSpeciesData <- bind_rows("animal" = conservancyAnimalSpeciesDataStandardized, 
                                            "plant" = conservancyPlantSpeciesDataStandardized,
                                            .id = "kingdom")

# Calculate matching species count
matchingSpeciesCount <- matchingSpecies %>% 
  group_by(reserve) %>% 
  filter(!is.na(reserve)) %>% 
  summarize(matching_species = n()) 

totalSpeciesCount <- combinedSpeciesData %>% 
  group_by(reserve) %>% 
  filter(!is.na(reserve)) %>% 
  summarize(total_species_in_reserve = n())

total_species_in_conservancy <- nrow(conservancyCombinedSpeciesData)

# Create tables comparing proportion of plants in conservancy also in reserve and vice versa 

speciesComparisonTable <- left_join(matchingSpeciesCount, totalSpeciesCount, 
                                   by = "reserve") %>% 
  mutate(proportion_matching_species_in_reserve = 
           matching_species / total_species_in_reserve) %>% 
  mutate(percent_matching_species_in_reserve = 
           paste0(format(100 * proportion_matching_species_in_reserve, 
         digits = 2), "%")) %>% 
  mutate(proportion_matching_species_in_conservancy = 
           matching_species / total_species_in_conservancy) %>% 
  mutate(percent_matching_species_in_conservancy = 
           paste0(format(100 * proportion_matching_species_in_conservancy, 
         digits = 1), "%")) %>% 
  arrange(desc(proportion_matching_species_in_reserve))

speciesComparisonTableConservancyEmphasis <- speciesComparisonTable %>% 
  arrange(desc(proportion_matching_species_in_conservancy)) %>% 
  select(reserve, matching_species, total_species_in_reserve,
         percent_matching_species_in_reserve, percent_matching_species_in_conservancy)

speciesComparisonTableShort <- speciesComparisonTable %>% 
  select(reserve, matching_species, total_species_in_reserve,
         percent_matching_species_in_reserve, percent_matching_species_in_conservancy)

# Visualize results
speciesComparisonTableViz <- speciesComparisonTableShort %>% 
  kable(format = "html", align = "lcccc", 
        col.names = gsub("_", " ", capitalize(colnames(speciesComparisonTableShort)))) %>% 
  kable_styling

speciesComparisonTableConservancyEmphasisViz <- speciesComparisonTableConservancyEmphasis %>% 
  kable(format = "html", align = "lcccc", 
        col.names = gsub("_", " ", capitalize(colnames(speciesComparisonTableConservancyEmphasis)))) %>% 
  kable_styling

speciesComparisonTableViz
speciesComparisonTableConservancyEmphasisViz

# Combine the species, animal, and plant data

animalsComparisonTableStd <- animalsComparisonTable
names(animalsComparisonTableStd) <- names(speciesComparisonTable)
plantsComparisonTableStd <- plantsComparisonTable
names(plantsComparisonTableStd) <- names(speciesComparisonTable)

allComparisonTable <- bind_rows("species" = speciesComparisonTable,
                                "animals" = animalsComparisonTableStd,
                                "plants" = plantsComparisonTableStd,
                                .id = "kingdom") %>% 
  arrange(desc(kingdom, matching_species))

allComparisonTableShort <- allComparisonTable %>% 
  select(kingdom, reserve, matching_species, total_species_in_reserve,
         percent_matching_species_in_reserve, percent_matching_species_in_conservancy)

allComparisonTableViz <- allComparisonTableShort %>% 
  kable(format = "html", align = "llcccc", 
        col.names = gsub("_", " ", capitalize(colnames(allComparisonTableShort)))) %>% 
  kable_styling

allComparisonTableViz

```


## Species Uniqueness Count

```{r Conservancy Plant Species with List of Reserves where Found}
# Find places where each matched species shows up in other reserves

matchingPlantsArranged <- matchingPlants %>% 
  arrange(genus, species, sublabel, reserve) 

matchingPlantsReserves <- matchingPlantsArranged  %>% 
  group_by(genus, species, sublabel) %>% 
  summarize(count = n()) 

# Add names of reserves each species is represented in at end:

matchingPlantsArranged$reserve_list <- ""

matchingPlantsArranged$reserve_list[1] <- paste0(matchingPlantsArranged$reserve[1])
idx = 2
idx_max = nrow(matchingPlantsArranged)

while(idx < idx_max) {
  n = 1
  while((setequal(matchingPlantsArranged[idx, 2:4], matchingPlantsArranged[(idx - 1), 2:4])) & (idx < idx_max)) {
    n = n + 1
    idx = idx + 1
  }
  matchingPlantsArranged$reserve_list[(idx - n):(idx - 1)] <- 
    paste(matchingPlantsArranged$reserve[(idx - n):(idx - 1)], collapse = ", ")
  idx = idx + 1
}

matchingPlantsArranged$reserve_list[idx_max] <- 
    paste(matchingPlantsArranged$reserve[idx_max])

# Combine the data

matchingPlantsReservesCombined <- matchingPlantsArranged %>% 
  distinct(genus, species, sublabel, reserve_list) %>% 
  right_join(matchingPlantsReserves, by = c("genus", "species", "sublabel")) %>% 
  arrange(count, genus, species)

matchingPlantsReservesCombined
```

```{r Conservancy Animal Species with List of Reserves where Found}

# Find places where each matched species shows up in other reserves

matchingAnimalsArranged <- matchingAnimals %>% 
  arrange(genus, species, sublabel, reserve) 

matchingAnimalsReserves <- matchingAnimalsArranged  %>% 
  group_by(genus, species, sublabel) %>% 
  summarize(count = n()) 

# Add names of reserves each species is represented in at end:

matchingAnimalsArranged$reserve_list <- ""

matchingAnimalsArranged$reserve_list[1] <- paste0(matchingAnimalsArranged$reserve[1])
idx = 2
idx_max = nrow(matchingAnimalsArranged)

while(idx < idx_max) {
  n = 1
  while((setequal(matchingAnimalsArranged[idx, 2:4], matchingAnimalsArranged[(idx - 1), 2:4])) & (idx < idx_max)) {
    n = n + 1
    idx = idx + 1
  }
  matchingAnimalsArranged$reserve_list[(idx - n):(idx - 1)] <- 
    paste(matchingAnimalsArranged$reserve[(idx - n):(idx - 1)], collapse = ", ")
  idx = idx + 1
}

matchingAnimalsArranged$reserve_list[idx_max] <- 
    paste(matchingAnimalsArranged$reserve[idx_max])

# Combine the data

matchingAnimalsReservesCombined <- matchingAnimalsArranged %>% 
  distinct(genus, species, sublabel, reserve_list) %>% 
  right_join(matchingAnimalsReserves, by = c("genus", "species", "sublabel")) %>% 
  filter(!is.na(species)) %>% 
  arrange(count, genus, species)

matchingAnimalsReservesCombined
```

```{r Conservancy Species with List of Reserves where Found}

# Find places where each matched species shows up in other reserves

matchingSpeciesCountByReserve <- bind_rows("animal" = matchingAnimalsReservesCombined, 
                                           "plant" = matchingPlantsReservesCombined,
                                           .id = "kingdom")

uniquePlants <- conservancyPlantData %>% 
  anti_join(ucnrsPlantDataSubset, by = c("genus", "species", "sublabel")) %>% 
  select(genus, species, sublabel) %>% 
  mutate(count = 0)

uniqueAnimals <- conservancyAnimalData %>% 
  anti_join(ucnrsAnimalDataSubset, by = c("genus", "species", "sublabel1")) %>% 
  select(genus, species, sublabel = sublabel1) %>% 
  mutate(count = 0) %>% distinct() 

uniqueSpecies <- bind_rows("animal" = uniqueAnimals, "plant" = uniquePlants, .id = "kingdom") 

matchingSpeciesWithUnique <- bind_rows(matchingSpeciesCountByReserve, uniqueSpecies) %>% 
  filter(!is.na(species)) %>% distinct() %>% 
  arrange(count, kingdom, genus, species, sublabel)

#Compute Number and Ratio of Rare and Unique Species

totalSpecies <- nrow(matchingSpeciesWithUnique)
totalAnimals <- matchingSpeciesWithUnique %>% 
  filter(kingdom == "animal") %>% 
  nrow()

rareOrUniqueSpecies <- matchingSpeciesWithUnique %>% filter(count < 4)

totalRareOrUniqueSpecies <- nrow(rareOrUniqueSpecies)
totalUniqueSpecies <- nrow(uniqueSpecies)

ratioRareOrUniqueSpecies <- totalRareOrUniqueSpecies / totalSpecies
ratioUniqueSpecies <- totalUniqueSpecies / totalSpecies

# Make a table for presentation

rareOrUniqueComparisonTable <- tibble("variable" = c("Unique Species (in no other reserve)", 
                                                     "Rare or Unique Species (in < 4 reserves)", 
                                                     "Total Species in Conservancy"), 
                                      "number" = c(totalUniqueSpecies, 
                                                   totalRareOrUniqueSpecies, 
                                                   totalSpecies), 
                                      "ratio" = c(ratioUniqueSpecies,
                                                  ratioRareOrUniqueSpecies,
                                                  1))

speciesComparisonTableViz <- kable(rareOrUniqueComparisonTable, 
                                  format = "html", align = "lcc", 
                                  col.names = capitalize(colnames(rareOrUniqueComparisonTable))) %>% 
  kable_styling

speciesComparisonTableViz

speciesBrokenDown <- kable(matchingSpeciesWithUnique, 
                                  format = "html", align = "lcc", 
                                  col.names = gsub("_", " ", capitalize(colnames(matchingSpeciesWithUnique)))) %>% 
  kable_styling
speciesBrokenDown

```

```{r Relative Rarity of Conservancy Species}

# Calculate Chart of Threshold for Species

speciesBelowReserveThreshold <- matchingSpeciesWithUnique %>% 
  group_by(count) %>% 
  rename(number_of_reserves = count) %>% 
  summarize(number_of_species_found_in_n_reserves = n()) %>% 
  mutate(number_of_species_found_in_n_or_fewer_reserves = 
           cumsum(number_of_species_found_in_n_reserves)) %>% 
  mutate(proportion_of_species_found_in_n_or_fewer_reserves = 
           number_of_species_found_in_n_or_fewer_reserves / 
           totalSpecies) %>%
  mutate(percent_of_species_found_in_n_or_fewer_reserves = 
           paste0(format(100 * proportion_of_species_found_in_n_or_fewer_reserves, 
         digits = 3), "%"))
  
speciesBelowReserveThreshold
  

# Calculate Chart of Threshold for Animals

animalsBelowReserveThreshold <- matchingSpeciesWithUnique %>% 
  group_by(count, kingdom) %>% 
  summarize(number_of_species_found_in_n_reserves = n()) %>% 
  filter(kingdom == "animal") %>% 
  select(number_of_reserves = count, 
         number_of_species_found_in_n_reserves) %>% 
  ungroup() %>% 
  mutate(number_of_species_found_in_n_or_fewer_reserves = 
           cumsum(number_of_species_found_in_n_reserves)) %>% 
  mutate(proportion_of_species_found_in_n_or_fewer_reserves = 
           number_of_species_found_in_n_or_fewer_reserves / 
           totalAnimals) %>%
  mutate(percent_of_species_found_in_n_or_fewer_reserves = 
           paste0(format(100 * proportion_of_species_found_in_n_or_fewer_reserves, 
         digits = 3), "%"))

animalsBelowReserveThreshold


# Calculate Chart of Threshold for Plants

plantsBelowReserveThreshold <- matchingSpeciesWithUnique %>% 
  group_by(count, kingdom) %>% 
  summarize(number_of_species_found_in_n_reserves = n()) %>% 
  filter(kingdom == "plant") %>% 
  select(number_of_reserves = count, 
         number_of_species_found_in_n_reserves) %>% 
  ungroup() %>% 
  mutate(number_of_species_found_in_n_or_fewer_reserves = 
           cumsum(number_of_species_found_in_n_reserves)) %>% 
  mutate(proportion_of_species_found_in_n_or_fewer_reserves = 
           number_of_species_found_in_n_or_fewer_reserves / 
           total_plant_species_in_conservancy) %>%
  mutate(percent_of_species_found_in_n_or_fewer_reserves = 
           paste0(format(100 * proportion_of_species_found_in_n_or_fewer_reserves, 
         digits = 3), "%"))

plantsBelowReserveThreshold

# Bind tables, combining by kingdom

speciesComparisonAllReserveNumbers <- bind_rows("species" = speciesBelowReserveThreshold,
                                                "animals" = animalsBelowReserveThreshold,
                                                "plants" = plantsBelowReserveThreshold,
                                                .id = "category")

speciesComparisonAllReserveNumbersShort <- speciesComparisonAllReserveNumbers %>% 
  filter(category == "species") %>% 
  select(number_of_reserves, number_of_species_found_in_n_reserves, 
         number_of_species_found_in_n_or_fewer_reserves, percent_of_species_found_in_n_or_fewer_reserves)

animalsComparisonAllReserveNumbersShort <- speciesComparisonAllReserveNumbers %>% 
  filter(category == "animals") %>% 
  select(number_of_reserves, number_of_species_found_in_n_reserves, 
         number_of_species_found_in_n_or_fewer_reserves, percent_of_species_found_in_n_or_fewer_reserves)

plantsComparisonAllReserveNumbersShort <- speciesComparisonAllReserveNumbers %>% 
  filter(category == "plants") %>% 
  select(number_of_reserves, number_of_species_found_in_n_reserves, 
         number_of_species_found_in_n_or_fewer_reserves, percent_of_species_found_in_n_or_fewer_reserves)

# Make a table for presentation

speciesComparisonAllReserveNumbersViz <- speciesComparisonAllReserveNumbersShort %>% 
  kable(format = "html", align = "rccc", 
        col.names = gsub("_", " ", capitalize(colnames(speciesComparisonAllReserveNumbersShort)))) %>% 
  kable_styling

animalsComparisonAllReserveNumbersViz <- animalsComparisonAllReserveNumbersShort %>% 
  kable(format = "html", align = "rccc", 
        col.names = gsub("_", " ", capitalize(colnames(animalsComparisonAllReserveNumbersShort)))) %>% 
  kable_styling

plantsComparisonAllReserveNumbersViz <- plantsComparisonAllReserveNumbersShort %>% 
  kable(format = "html", align = "rccc", 
        col.names = gsub("_", " ", capitalize(colnames(plantsComparisonAllReserveNumbersShort)))) %>% 
  kable_styling

speciesComparisonAllReserveNumbersViz
animalsComparisonAllReserveNumbersViz
plantsComparisonAllReserveNumbersViz
```

## Summary Statistics

```{r Plots of Conservancies with Closest Matches of Species}

# Create a long-format comparison table should we need it

allComparisonTableLong <- allComparisonTable %>% 
  gather(proportion_matching_species_in_reserve,
         proportion_matching_species_in_conservancy,
         key = "proportion_type", value = "proportion")

# Order reserve by factors so as to use in plots

speciesComparison <- allComparisonTable %>% 
  filter(kingdom == "species")

speciesComparison$reserve <- 
  factor(speciesComparison$reserve,
         levels = unique(speciesComparison$reserve)[order(speciesComparison$proportion_matching_species_in_reserve,
                                                          decreasing = TRUE)])

# Set margins

margins <- list(l = 200, r = 0, b = 0, t = 40, pad = 0.5)

# Plot % species present in each reserve that are also in the conservancy

speciesComparison %>% 
  plot_ly(y = ~reserve, 
          x = ~proportion_matching_species_in_reserve,
          type = "bar", 
          name = "Proportion of Matching Species in Reserves (out of 1)",
          orientation = "h",
          width = 1100,
          height = 670) %>% 
  add_trace(x = ~proportion_matching_species_in_conservancy,
            name = "Proportion of Matching Species in Conservancy (out of 1)") %>% 
  layout(title = "Proportion/Percent of Matching Species per Reserve",
         yaxis = list(title = "Reserves", b = 20),
         xaxis = list(title = ""),
         
         barmode = "group",
         autosize = FALSE,
         margin = margins,
         legend = list(orientation = "h",
                       x = 0, b = 0)) %>% 
  add_annotations(x = speciesComparison$proportion_matching_species_in_conservancy,
                  y = speciesComparison$reserve,
                  text = speciesComparison$percent_matching_species_in_conservancy,
                  xref = "x", yref = "y",
                  showarrow = TRUE, arrowhead = 4, arrowsize = .01,
                  ax = 20, ay = -4.5) %>% 
  add_annotations(x = speciesComparison$proportion_matching_species_in_reserve,
                  y = speciesComparison$reserve,
                  text = speciesComparison$percent_matching_species_in_reserve,
                  xref = "x", yref = "y",
                  showarrow = TRUE, arrowhead = 4, arrowsize = .01,
                  ax = 20, ay = 3)
  
             
```


```{r Plots of Conservancies with Closest Matches of Animal}

# Order reserve by factors so as to use in plots

animalsComparison <- allComparisonTable %>% 
  filter(kingdom == "animals")

animalsComparison$reserve <- 
  factor(animalsComparison$reserve,
         levels = unique(animalsComparison$reserve)[order(animalsComparison$proportion_matching_species_in_reserve,
                                                          decreasing = TRUE)])

# Set margins

margins <- list(l = 200, r = 0, b = 0, t = 40, pad = 0.5)

# Plot % species present in each reserve that are also in the conservancy

animalsComparison %>% 
  plot_ly(y = ~reserve, 
          x = ~proportion_matching_species_in_reserve,
          type = "bar", 
          name = "Proportion of Matching Animal Species in Reserves (out of 1)",
          orientation = "h",
          width = 1100,
          height = 600) %>% 
  add_trace(x = ~proportion_matching_species_in_conservancy,
            name = "Proportion of Matching Animal Species in Conservancy (out of 1)") %>% 
  layout(title = "Proportion/Percent of Matching Animal Species per Reserve",
         yaxis = list(title = "Reserves", r = 50),
         xaxis = list(title = ""),
         barmode = "group",
         autosize = FALSE,
         margin = margins,
         legend = list(orientation = "h",
                       x = 0, b = 0)) %>% 
  add_annotations(x = animalsComparison$proportion_matching_species_in_reserve,
                  y = animalsComparison$reserve,
                  text = animalsComparison$percent_matching_species_in_reserve,
                  xref = "x", yref = "y",
                  showarrow = TRUE, arrowhead = 4, arrowsize = .01,
                  ax = 20, ay = 4) %>% 
  add_annotations(x = animalsComparison$proportion_matching_species_in_conservancy,
                  y = animalsComparison$reserve,
                  text = animalsComparison$percent_matching_species_in_conservancy,
                  xref = "x", yref = "y",
                  showarrow = TRUE, arrowhead = 4, arrowsize = .01,
                  ax = 20, ay = -5)
             
```

```{r Plots of Reserves with Closest Matches of Plants}

# Order reserve by factors so as to use in plots

plantsComparison <- allComparisonTable %>% 
  filter(kingdom == "plants")

plantsComparison$reserve <- 
  factor(plantsComparison$reserve,
         levels = unique(plantsComparison$reserve)[order(plantsComparison$proportion_matching_species_in_reserve,
                                                          decreasing = TRUE)])

# Set margins

margins <- list(l = 200, r = 0, b = 0, t = 40, pad = 0.5)

# Plot % species present in each reserve that are also in the conservancy

plantsComparison %>% 
  plot_ly(y = ~reserve, 
          x = ~proportion_matching_species_in_reserve,
          type = "bar", 
          name = "Proportion of Matching Plant Species in Reserves (out of 1)",
          orientation = "h",
          width = 1100,
          height = 600) %>% 
  add_trace(x = ~proportion_matching_species_in_conservancy,
            name = "Proportion of Matching Plant Species in Conservancy (out of 1)") %>% 
  layout(title = "Proportion/Percent of Matching Plant Species per Reserve",
         yaxis = list(title = "Reserves", r = 50),
         xaxis = list(title = ""),
         barmode = "group",
         autosize = FALSE,
         margin = margins,
         legend = list(orientation = "h",
                       x = 0, b = 0)) %>% 
  add_annotations(x = plantsComparison$proportion_matching_species_in_reserve,
                  y = plantsComparison$reserve,
                  text = plantsComparison$percent_matching_species_in_reserve,
                  xref = "x", yref = "y",
                  showarrow = TRUE, arrowhead = 4, arrowsize = .01,
                  ax = 20, ay = 4) %>% 
  add_annotations(x = plantsComparison$proportion_matching_species_in_conservancy,
                  y = plantsComparison$reserve,
                  text = plantsComparison$percent_matching_species_in_conservancy,
                  xref = "x", yref = "y",
                  showarrow = TRUE, arrowhead = 4, arrowsize = .01,
                  ax = 20, ay = -5)
             
```

```{r Plots of Number of Rare Species}

# Prepare and otherwise Spread data for plotly use

speciesCounts <- speciesComparisonAllReserveNumbers %>% 
  select(category, number_of_reserves, number_of_species_found_in_n_or_fewer_reserves, 
         percent_of_species_found_in_n_or_fewer_reserves) %>% 
  filter(category == "species") %>% 
  select(-category)

speciesCountsDisaggregated <- speciesComparisonAllReserveNumbers %>% 
  select(category, number_of_reserves, number_of_species_found_in_n_or_fewer_reserves) %>% 
  filter(category %in% c("plants", "animals")) %>% 
  spread(category, number_of_species_found_in_n_or_fewer_reserves, 
         sep = "_number_of_species_found_in_n_or_fewer_reserves_") %>% 
  left_join(speciesCounts, by = "number_of_reserves") 

speciesCountsDisaggregated$category_number_of_species_found_in_n_or_fewer_reserves_plants[which(speciesCountsDisaggregated$number_of_reserves == 23)] <- 963
speciesCountsDisaggregated$category_number_of_species_found_in_n_or_fewer_reserves_plants[which(is.na(speciesCountsDisaggregated$category_number_of_species_found_in_n_or_fewer_reserves_plants))] <- 964

# Set margins

margins <- list(l = 50, r = 0, b = 50, t = 30, pad = 0.5)

# Plot % species present in each reserve that are also in the conservancy

speciesCountsDisaggregated %>% 
  plot_ly(x = ~number_of_reserves, 
          y = ~number_of_species_found_in_n_or_fewer_reserves,
          type = "scatter", 
          mode = "lines",
          fill = "tozeroy",
          name = "Plant Species Found in X or Fewer Reserves",
          width = 1200,
          height = 500) %>% 
  add_trace(y = ~category_number_of_species_found_in_n_or_fewer_reserves_animals,
            name = "Animal Species Found in X or Fewer Reserves",
            fill = "tozeroy") %>% 
  layout(title = "Number of Species in Conservancy Found in X or Fewer Reserves",
         yaxis = list(title = "# of Conservancy Species", b = 20),
         xaxis = list(title = "# of Reserves (X)", dtick = 1),
         autosize = FALSE,
         margin = margins,
         legend = list(orientation = "h", x = 0.01, y = 1)) %>% 
  add_annotations(x = speciesCountsDisaggregated$number_of_reserves,
                  y = speciesCountsDisaggregated$number_of_species_found_in_n_or_fewer_reserves,
                  text = speciesCountsDisaggregated$percent_of_species_found_in_n_or_fewer_reserves,
                  xref = "x", yref = "y",
                  showarrow = TRUE, arrowhead = 7, arrowsize = .001,
                  ax = 15, ay = 20) %>% 
  add_annotations(x = speciesCountsDisaggregated$number_of_reserves,
                  y = speciesCountsDisaggregated$number_of_species_found_in_n_or_fewer_reserves,
                  text = speciesCountsDisaggregated$number_of_species_found_in_n_or_fewer_reserves,
                  xref = "x", yref = "y",
                  showarrow = TRUE, arrowhead = 7, arrowsize = .001,
                  ax = 5, ay = -20)
  
             
```